### ISSUE TITLE
Why all the read buffering?

### ISSUE THREAD

**Issue by Xeoncross** [flashmob/go-guerrilla#13]
There seems to be a [lot of buffering structs added](https://github.com/flashmob/go-guerrilla/blob/master/smtpd.go#L289). Why are they being used? Was the go defaults for reading from an io.Reader unsafe?

Are you trying to limit the amount read? You could use an `io.LimitReader()`:

    data, err := ioutil.ReadAll(io.LimitReader(client.conn, 1000000))

**Comment by flashmob** [comment]
There were two reasons; 
1. Wanted to 'extend' the buffio.Reader so that it has a limited reader underneath plus add a setLimit() method to adjust the limit. (Didn't want to allocate a new limitedreader each time)
2. wanted to 'extend' the limited reader so the limit could adjust the limit. The other problem was that limit reader returned io.EOF when limit reached, but needed a more specific error

**Comment by flashmob** [comment]
Thanks for your review btw! After having a second look at it, it looks like the err handling should have been placed inside the limited reader, then there is no need for readLimitedString() - can just use good old bufio.readString()
