### ISSUE TITLE
Header detection issue

### ISSUE THREAD

**Issue by iwex** [flashmob/go-guerrilla#139]
I have some problem with headers.
I testes it with `swaks`, it sends valid headers, but Guerrilla can't parse headers and gives me error:
```
DEBU[0001] Client sent: DATA
DEBU[0001] Writing response to client: 54 Enter message, ending with '.' on a line by itself
ERRO[0001] parse headers error error=EOF
```
I tested it with `swaks -f me@example.org -t test@example.com --server 127.0.0.1:2525`

**Comment by flashmob** [comment]
Hi, thanks for the report.
Do you know what is the full input that is fed to the DATA command? Please
paste a sample here.

**Comment by iwex** [comment]
@flashmob sure
```
=== Trying localhost:2525...
=== Connected to localhost.
<-  220 iwex-pc SMTP Guerrilla(unknown) #1 (1) 2019-03-15T15:26:53+02:00
 -> EHLO iwex-pc
<-  250-iwex-pc Hello
<-  250-SIZE 10485760
<-  250-PIPELINING
<-  250-ENHANCEDSTATUSCODES
<-  250 HELP
 -> MAIL FROM:<me@example.org>
<-  250 2.1.0 OK
 -> RCPT TO:<test@example.com>
<-  250 2.1.5 OK
 -> DATA
<-  354 Enter message, ending with '.' on a line by itself
 -> Date: Fri, 15 Mar 2019 15:26:53 +0200
 -> To: test@example.com
 -> From: me@example.org
 -> Subject: test Fri, 15 Mar 2019 15:26:53 +0200
 -> Message-Id: <20190315152653.027193@iwex-pc>
 -> X-Mailer: swaks v20181104.0 jetmore.org/john/code/swaks/
 -> 
 -> This is a test mailing
 -> 
 -> 
 -> .
<-  250 2.0.0 OK: queued as a04ac137fdce82ed46362ca1daf0399d
 -> QUIT
<-  221 2.0.0 Bye
```

**Comment by codestation** [comment]
I have the same problem. The error comes from [here](https://github.com/flashmob/go-guerrilla/blob/cb550348c44e511bc1a6f71262f59ff41c85ed2c/mail/envelope.go#L133).

From the [ReadMIMEHeader](https://golang.org/pkg/net/textproto/#Reader.ReadMIMEHeader) documentation it expects a blank line at the end but the header slice doesn't include it.

IMO the fix can be like this.

``` go
header := buf[0:headerEnd+2]
```

It won't be out of bounds because the `Index` call before it made sure that those two bytes exists.
