### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by remohammadi** [flashmob/go-guerrilla#14]
In order to write *unit* tests, I want to extract storing mechanism (`save_mail.go`) from the code and move it into a package. Would you accept such refactoring? Are you ok with [this layouting](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1)? Thanks :)

**Comment by flashmob** [comment]
Yeah, sounds good! :+1: 
What do you think about separating the save_mail part to use a "hook" style architecture?

For example, if you have a look at: https://github.com/Sirupsen/logrus, scroll down to the hook section, they have all different hooks for different back-ends, maybe a similar pattern could be used for us too?

**Comment by remohammadi** [comment]
That's a great pattern to use.

To fire the right hook for the received email, we need a choosing mechanism. logrus uses log level to choose which hooks should be fired on every log entry. I can think of some candidates, like domain name of the receiver, to be the key for choosing the hook. We can also pass the whole message and ask the hooks if they accept this message.

So here we have 3 options:
* hooks get registered paired with a (or multi) host name(s)
* hooks get registered in order, and we check them in order until one of them accepts the message
* a hook (specified by the config file) gets registered, and handles all the messages.

I guess we can extend the third option to the other ones. So, is it ok to start with the 3rd option?

**Comment by flashmob** [comment]
Thanks for the feedback! Yes, for now lets use the 3rd option only, where a specific save_mail backend can configured for each server.

As for the word hook...Maybe call it 'plugin' since it's the most common terminology?

Wow, getting exciting! Looking forward to all the different saving backends getting developed in the future, eg Maildir would be useful.. another one would be a Rabbit MQ as [someone suggested](https://github.com/flashmob/go-guerrilla/issues/8). 

Btw, in the future, would need to re-design the save mail function to allow streaming of data coming from the DATA command. This is to save memory so that in the future the server could handle really large attachments. So the way it would work:

1. At the beginning of the DATA command, send the headers of the email to the save_mail backend and return with an email id / guid of the email
2. While in the DATA command, send the data in chunks (steam) to the save_mail backend
3. At the end of the DATA command, notify the backend that the email has finished.

**Comment by Xeoncross** [comment]
So send a channel and just close it at the end of the DATA command? 

You could also just pass the connection reader and let save_mail call a helper function (so you don't have to put that logic in save_mail) to read each bit of the buffer.

**Comment by flashmob** [comment]
Yep, there would be two ways to do it, one with channels the other without. Currently it is using an unbuffered channel to wait until saving is done, and one great feature of channels is the ability to do select and timeout... However, after considering, perhaps the saving backend should be concerned with timeout instead?. 
Passing a reader sound like a good idea.
A new branch for this and will be up for you guys to review soon including a new save mail interface!

**Comment by remohammadi** [comment]
About the terminology, is it ok to use *backend* instead? They won't be much plugable after compiling (until [these codes](https://github.com/golang/go/commit/0cbb12f0bbaeb3893b3d011fdb1a270291747ab0) are released).

I will create a pull request with the simplest way to handle the connection tonight or tomorrow morning. It will be easy to refactor it in another commits 😉

**Comment by flashmob** [comment]
Cool, looks like real plugins are coming to Go in the future!
Ok, 'backend' makes sense.
Looking forward to the refactor & tests. Thank you
