### ISSUE TITLE
Subject starts with ?utf-8?q?b2a9c4ea0f353f9c7f9583b54bbe348a2cc42=5F=5F?=

### ISSUE THREAD

**Issue by rami-dabain** [flashmob/go-guerrilla#39]
Some web mail client [SOGo] send the subject starting with ?utf-8?q?the subject....
Shall it be decoded within go-guerrilla?

**Comment by flashmob** [comment]
This is mime encoded header.  You can decode using https://golang.org/pkg/mime/#WordDecoder.DecodeHeader
We also have our own convenience function in utils.go since it used iconv library, more encoding supported.
We leave all decoding down to the backends. 
See example https://github.com/flashmob/go-guerrilla/blob/master/backends/guerrilla_db_redis.go
