### ISSUE TITLE
[Question] Stop output

### ISSUE THREAD

**Issue by rami-dabain** [flashmob/go-guerrilla#47]
Hi, How can i tell the package to stop outputting ?

**Comment by flashmob** [comment]
Assuming you mean the log messages? 
When running, you can redirect the output to whatever file, including /dev/null
Assuming you have a bash shell.

For example, if you want to discard everything:

`./guerrillad serve >> /dev/null 2>&1 &`

Or you want to save it:

`./guerrillad serve >> /home/mike/smtpd_log 2>&1 &`

The >> mean redirect-and-append.
The 2>&1 means redirect errors and output.
The & at the end means run it in the background. 

You can than open another console and tail it

`tail -f /home/mike/smtpd_log`

**Comment by rami-dabain** [comment]
That is an obvious thing. but what if the package is a part of your software? you want to store the software log to examine it, but dont want to store the guerrilla log? isn't there an option to turn logging off?

**Comment by flashmob** [comment]
Yes, you can also control it programmatically too. The package uses logrus which gives you a lot of control https://github.com/sirupsen/logrus

Try this

1. Import: log "github.com/Sirupsen/logrus"
2. At the start of your program: log.SetOutput(os.DevNull)

Since the argument to SetOutput is a writer, you can also feed it your own writer. See guerrilla_test.go init() func to see how it's done to a buffer.

You can also control the debug level, eg:
log.SetLevel(log.DebugLevel)
or 
log.SetLevel(log.FatalLevel)


Logurus also supports hooks, but haven't tried them yet.

Anyway, to make it easier, the ability control output via config will be added in the future release. See #21

**Comment by rami-dabain** [comment]
It worked. thanks
`ioutil.Discard`
