### ISSUE TITLE
Don't advertise STARTTLS if certificate loading fails

### ISSUE THREAD

**Issue by dapaxx** [flashmob/go-guerrilla#66]
If loading the certificate fails, we must not advertise STARTTLS nor we should open an TLS-only host.
A check is to be implemented, if the configured certificate is existing and maybe even a check if it is valid.

**Comment by flashmob** [comment]
Cool, that would be more pragmatic!

Would need to add certificate file existence checks in config.go

and call it when it's loaded in func `Load`. Then modify the boolean config vales based on the test result.
The tricky part is config reloading. 

And then the config should take effect for the next connected client

Perhaps this issue is also related to Lets Encrypt #29

**Comment by dapaxx** [comment]
I've created a quick fix for disabling STARTTLS if the certificate loading fails or the server alltogther if it is TLS only.
