### ISSUE TITLE
Priviledge separation

### ISSUE THREAD

**Issue by themester** [flashmob/go-guerrilla#89]
Hello.

When you executes guerrillad server as root the run with 0 uid (root uid).
I propose you to add priviledge separation using something function similar to https://golang.org/pkg/os/#StartProcess

You can read about github.com/sevlyar/go-daemon using daemons and handling processes in background with gouroutine functionality.

Thank you!

**Comment by flashmob** [comment]
Hi,

Unfortunately golang doesn't have a neat solution to this problem. The `setuid` and `setguid` functions have been disabled, and the workarounds that you have linked to seem to have limitations / trade-offs. 

Although there's some good news! On POSIX systems, one may use `setcap` to run the daemon using a higher uid while giving it permissions to bind on port 25 like so:

`sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/guerrillad`

Other alternatives:

- create an AppArmour profile, eg. https://www.digitalocean.com/community/tutorials/how-to-create-an-apparmor-profile-for-nginx-on-ubuntu-14-04

- run in a vm / container, lock down using their respective tooling

**Comment by themester** [comment]
Thank you for the temporary solution!

But I made an SSH Server which implements a priviledge separation. Only works if you want to run a process like a shell (I did not see the code of guerrillad, I will do in the next days...), but I can show you the part of code if you could implement:
```go
cmd, err := os.StartProcess(users[Conn.User].Shell, []string{users[Conn.User].Shell}, &os.ProcAttr{
    Dir: users[Conn.User].Home,
    Files: []*os.File{
      tty, tty, tty,
    },
    // configuring env like OpenSSH server
    Env: Conn.Env,
    // privilege separation
    Sys: &syscall.SysProcAttr{
      Credential: &syscall.Credential{
        Uid: users[Conn.User].UID,
        Gid: users[Conn.User].GID,
      },
      Setsid:  true,
      Setctty: true,
    },
  })
```

**Comment by flashmob** [comment]
Could you explain how does that work?  So does this mean the root process opens a privileged port and then passes it to the newly opened process? Does the root process continue to run and monitor the children? Does the root process communicate to the children (eg. via pipes) and forward any signals / commands? Likewise, can the children communicate back to the parent?

Guerrillad already has some daemonisation functionality, including capturing of signals, re-loading the configuratoon and re-opening the log files. So any.new functionality in this are would also need to consider this. For example, when guerrillad starts it writes the pid into a file. From there you can send it signals such as SIGHUP to reload the configuration.

**Comment by themester** [comment]
@flashmob The function StartProcess starts new process with ProcAttr attributes. In summary this function will do a fork exec.
In this case the server (root process) starts user default shell the following arguments in ProcAttr:
Dir: Default directory when the command will run. In my case user home.
Files: Are the related files, the first corresponds with STDIN (descriptor 0), the second with STDOUT (descriptor 1), and third with STDERR (descriptor 2). I can add more than 3, but I want to send only STDIN, STDOUT and STDERR though TTY.
Sys: Is the SysProcAttr structure. Inside this structure I specify the options that process will have. In this case the process will be run as user authenticated pid and gid, and the flags setsid and setctty activated.

You can do a pipe to communicate two process. Only you have to add the pipe descriptor into `Files` attribute as the fourth argument (OR the second if you want to receive STDOUT though pipe).
If you want to add log opened file to the child process only you have to add the *os.File structure to `Files` attribute.

The unique problem is that you cannot use goroutines or similar, because the process is different that golang runtime process.

**Comment by flashmob** [comment]
Thanks for the details. One detail that's still not clear is how would the forked process be able to get a socket listener that is opened on port 25? 

It may be also good to investigate to see how other more mature projects deal with this issue. One good example would be the Caddy Server https://github.com/mholt/caddy - they also seem to use the `setcap` approach.

**Comment by themester** [comment]
You can use this function to get the os.File structure: https://golang.org/pkg/net/#TCPConn.File

When you got the os.File structure you have to parse to `Files` attribute in os.StartProcess

**Comment by flashmob** [comment]
So does that mean that it will be opening up a new process for each individual connection?

**Comment by themester** [comment]
No. I want to execute core process of the server as non-root priviledge.

**Comment by flashmob** [comment]
Yes, understand. Just want to know more details about how it would work. 

So, to re-prase the question above, assuming that TCPConn is the already established connection which is returned from net.Listen() - so would this mean that the core process would be blocking on net.Listen() and then call os.StartProcess() to pass the TCPConn to the new process?

**Comment by flashmob** [comment]
Hey, check this out, awesome article about isolation using namespaces: https://www.infoq.com/articles/build-a-container-golang

Although, it's questionable if something like this should be included in the server - tools such as Docker already provide this functionality, still a good read.

**Comment by flashmob** [comment]
Hey, btw, hopefully you are not being discouraged from contributing. You've raised some valid points, and opened up some good discussion. Sorry to have dragged it out for so long, however, after carefully considering this feature, it may be best to decline or at least defer for some other time.

It seems like the pattern of managing 'Privilege separation' inside the server is an old outdated pattern left over from the old Unix days. The disadvantages are that it can be more error prone, non-consistent, and these days the administrator has many other options and tools. These tools are provided by the operating system (eg. sandbox, `setcap`, SELinux style AppArmour, ...) and one can use container technologies such as Docker / Kubernetes to easily administer this. The same kind of pattern is seen in other modern operating systems, eg. in Android & iOS, where the privileges are governed by the OS in a standard unified way, instead of individually by each application.

One area that would welcome contribution would be to help create the Docker / Kubernetes images for building and running so that admins can be up and running fast in the recommended way.

Another area would be to make administartion easier, to have init scripts / startup scripts, similar to how they have here: https://github.com/mholt/caddy/tree/master/dist/init

Related, it would be great to add the ability for the build server (Travis) to automatically build .deb and .rpm packages and have them uploaded to a repo, so that it will become easier for admins to install/update the software.
